# West Virginia Project
# Shiny App
# Tiffany Wu
# 4/17/26

# setwd("//soe-shared.m.storage.umich.edu/soe-shared/Boston PK3/step3/Tiffany/West Virginia Project")

# Read in libraries
library(shiny)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(DT)
library(sf)
library(readr)
library(readxl)
library(scales)
library(htmltools)

select <- dplyr::select

# Null-coalescing helper. Shiny defines this internally but has not always
# exported it, so define it here rather than depend on the version in use.
`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a

options(shiny.launch.browser = TRUE)

# =========================
# 0. STATIC ASSETS
# =========================
# Make sure Shiny can serve files under www/ no matter how the app is launched
# (runApp(), Run App button, sourced, working dir set elsewhere, etc.).
# We resolve the absolute path of the www/ folder and register two prefixes:
#   /static/    -> www/                    (e.g. /static/wv_flag.jpg)
#   /map_files/ -> www/map_files/          (preserves the iframe's relative
#                                           links into enrollment_change_map_files/)
local({
  # Try to find the directory this script lives in.
  app_dir <- tryCatch({
    f <- sys.frame(1)$ofile
    if (is.null(f)) stop("not sourced")
    dirname(normalizePath(f, mustWork = FALSE))
  }, error = function(e) {
    # Fallback to the current working directory.
    getwd()
  })

  www_dir <- file.path(app_dir, "www")
  if (!dir.exists(www_dir)) www_dir <- normalizePath("www", mustWork = FALSE)

  if (dir.exists(www_dir)) {
    shiny::addResourcePath("static", www_dir)
    map_dir <- file.path(www_dir, "map_files")
    if (dir.exists(map_dir)) {
      shiny::addResourcePath("map_files", map_dir)
    }
    message("Registered Shiny resource paths from: ", www_dir)
  } else {
    warning("www/ folder not found near app.R — images and the map iframe may 404.")
  }
})

# =========================
# 1. READ RAW DATA
# =========================
school_existence          <- read_excel("school_existence.xlsx")
school_composition        <- read_excel("school_composition.xlsx")
district_enrollment_panel <- read.csv("district_enrollment_panel.csv")
census_raw                <- read_csv("wv_2011_2024.csv")

# School-age (5-17) population from the ACS 5-year tables, generated by the
# "School-age population" chunk in census_data.qmd. Optional: if the file is
# absent the dashboard still runs and the school-age line is simply omitted,
# so a fresh clone without a Census API key is not blocked.
school_age_path <- "wv_school_age_2011_2024.csv"
if (file.exists(school_age_path)) {
  school_age_raw <- read_csv(school_age_path, show_col_types = FALSE)
  message("Loaded ACS school-age population: ", nrow(school_age_raw),
          " county-years covering ",
          min(school_age_raw$year, na.rm = TRUE), "-",
          max(school_age_raw$year, na.rm = TRUE), ".")
} else {
  warning(school_age_path, " not found - the school-age population line will ",
          "be omitted. Run the ACS chunk in census_data.qmd to generate it.")
  school_age_raw <- tibble::tibble(
    year           = integer(0),
    county         = character(0),
    school_age_pop = numeric(0)
  )
}

# Same quantity from the Population Estimates Program (CC-EST AGESEX files,
# AGE513_TOT + AGE1417_TOT). Generated by the PEP chunk in census_data.qmd.
# Carried alongside the ACS series rather than replacing it so the two sources
# can be compared directly on the chart. Also optional.
school_age_pep_path <- "wv_school_age_pep_2011_2025.csv"
if (file.exists(school_age_pep_path)) {
  school_age_pep_raw <- read_csv(school_age_pep_path, show_col_types = FALSE)
  message("Loaded PEP school-age population: ", nrow(school_age_pep_raw),
          " county-years covering ",
          min(school_age_pep_raw$year, na.rm = TRUE), "-",
          max(school_age_pep_raw$year, na.rm = TRUE), ".")
} else {
  warning(school_age_pep_path, " not found - the PEP school-age line will be ",
          "omitted. Run the PEP chunk in census_data.qmd to generate it.")
  school_age_pep_raw <- tibble::tibble(
    year               = integer(0),
    county             = character(0),
    school_age_pop_pep = numeric(0)
  )
}

# Preserve the original Type from the .xlsx files BEFORE the pipeline rewrites
# them, so we can compare three sources side-by-side later:
#   Type_raw      = original Type column from school_existence / school_composition
#   Type          = result of the existing pipeline (school_year_enrollment_types.csv
#                   + standardize_type + elem_middle_schools override)
#   Type_inferred = final_type from inferred_school_types_final.csv
school_existence$Type_raw   <- school_existence$Type
school_composition$Type_raw <- school_composition$Type

# =========================
# 1.0 FILTER TO THE 55 WV COUNTY DISTRICTS
# =========================
# Only keep rows whose district matches one of these 55 counties (case-insensitive,
# after squishing whitespace). Each raw input source has its own native
# district column — we filter using whatever that column is called:
#   school_existence          -> "District"
#   school_composition        -> "District"
#   district_enrollment_panel -> "District"
#   wv_2011_2024.csv (census) -> "county"   (no "District" column in this file)
# Anything outside this list (state-wide programs, virtual academies, blank rows,
# typos) is dropped here so it never enters the rest of the pipeline.
ALLOWED_DISTRICTS <- toupper(c(
  "Barbour", "Berkeley", "Boone", "Braxton", "Brooke", "Cabell", "Calhoun", "Clay",
  "Doddridge", "Fayette", "Gilmer", "Grant", "Greenbrier", "Hampshire", "Hancock",
  "Hardy", "Harrison", "Jackson", "Jefferson", "Kanawha", "Lewis", "Lincoln", "Logan",
  "Marion", "Marshall", "Mason", "McDowell", "Mercer", "Mineral", "Mingo", "Monongalia",
  "Monroe", "Morgan", "Nicholas", "Ohio", "Pendleton", "Pleasants", "Pocahontas",
  "Preston", "Putnam", "Raleigh", "Randolph", "Ritchie", "Roane", "Summers", "Taylor",
  "Tucker", "Tyler", "Upshur", "Wayne", "Webster", "Wetzel", "Wirt", "Wood", "Wyoming"
))

keep_district <- function(df, col) {
  key    <- toupper(stringr::str_squish(as.character(df[[col]])))
  before <- nrow(df)
  out    <- df[key %in% ALLOWED_DISTRICTS, , drop = FALSE]
  message(sprintf("District filter on %s$%s: kept %d of %d rows",
                  deparse(substitute(df)), col, nrow(out), before))
  out
}

school_existence          <- keep_district(school_existence,          "District")
school_composition        <- keep_district(school_composition,        "District")
district_enrollment_panel <- keep_district(district_enrollment_panel, "District")
census_raw                <- keep_district(census_raw,                "county")

# Build the census frame the rest of the app expects (renames county -> District
# for downstream joins, and year -> Year).
census <- census_raw %>%
  mutate(District = county,
         Year     = year)

# Attach ACS school-age population onto the same District/Year grid. Counties
# missing from the ACS file keep an NA here, which ggplot drops from the line
# rather than drawing a break to zero.
census <- census %>%
  left_join(
    school_age_raw %>%
      transmute(
        District       = stringr::str_squish(as.character(county)),
        Year           = as.integer(year),
        school_age_pop = as.numeric(school_age_pop)
      ) %>%
      distinct(District, Year, .keep_all = TRUE),
    by = c("District", "Year")
  ) %>%
  left_join(
    school_age_pep_raw %>%
      transmute(
        District           = stringr::str_squish(as.character(county)),
        Year               = as.integer(year),
        school_age_pop_pep = as.numeric(school_age_pop_pep)
      ) %>%
      distinct(District, Year, .keep_all = TRUE),
    by = c("District", "Year")
  )

# Replace Type in school_composition with version without NAs
school_types <- read.csv("school_year_enrollment_types.csv")

school_composition <- school_composition %>%
  mutate(Schl = as.character(Schl)) %>%
  select(-Type) %>%
  left_join(
    school_types %>%
      mutate(school_code = as.character(school_code)) %>%
      distinct(school_code, .keep_all = TRUE) %>%
      select(school_code, school_type) ,
    by = c("Schl" = "school_code")
  ) %>%
  rename(Type = school_type)  %>%
  mutate(
    Type = case_when(
      is.na(Type) & str_detect(str_to_lower(School), "elementary") ~ "Elementary",
      is.na(Type) & str_detect(str_to_lower(School), "middle") ~ "Middle",
      is.na(Type) & str_detect(str_to_lower(School), "primary") ~ "Primary",
      is.na(Type) & str_detect(str_to_lower(School), "high school") ~ "High School",
      TRUE ~ Type
    )
  )

school_types_clean <- school_types %>%
  mutate(
    local_school_id = as.character(local_school_id),
    local_school_id = stringr::str_remove(local_school_id, "^0+")
  ) %>%
  select(local_school_id, school_type) %>%
  distinct(local_school_id, .keep_all = TRUE)

school_existence <- school_existence %>%
  mutate(
    Schl_ID = as.character(Schl_ID),
    Schl_ID_join = stringr::str_remove(Schl_ID, "^0+")
  ) %>%
  select(-Type) %>%
  left_join(
    school_types_clean,
    by = c("Schl_ID_join" = "local_school_id")
  ) %>%
  rename(Type = school_type) %>%
  select(-Schl_ID_join)

# Change type in school_status
# Replace Type in school_status
school_existence <- school_existence %>%
  mutate(
    Schl_ID = as.character(Schl_ID),
    Schl_ID_join = stringr::str_remove(Schl_ID, "^0+")
  ) %>%
  select(-Type) %>%
  left_join(
    school_types_clean,
    by = c("Schl_ID_join" = "local_school_id")
  ) %>%
  rename(Type = school_type) %>%
  select(-Schl_ID_join)  %>%
  mutate(
    Type = case_when(
      is.na(Type) & str_detect(str_to_lower(School), "elementary") ~ "Elementary",
      is.na(Type) & str_detect(str_to_lower(School), "middle") ~ "Middle",
      is.na(Type) & str_detect(str_to_lower(School), "primary") ~ "Primary",
      is.na(Type) & str_detect(str_to_lower(School), "high school") ~ "High School",
      TRUE ~ Type
    )
  )

# =========================
# 1a. LOAD INFERRED SCHOOL TYPES (joined on SchlID, not school name)
# =========================
# Loads final_type from inferred_school_types_final.csv and attaches it as
# Type_inferred alongside the existing Type column. The merge key is SchlID
# (6-digit district+local school code), which is more stable than the school
# name. The inferred file's own School column is also carried through as
# School_inferred so we can verify in section 3a whether the SchlID match
# actually points to the same school (school codes are occasionally reused
# after closures/consolidations).

# Zero-pad a school identifier to a 6-character string for matching.
pad_schlid <- function(x) {
  x <- stringr::str_squish(as.character(x))
  x <- stringr::str_pad(x, width = 6, side = "left", pad = "0")
  x
}

# Helper to normalize names for similarity scoring (used only in verification,
# not in the join itself).
normalize_school_name <- function(x) {
  x <- stringr::str_to_upper(x)
  x <- stringr::str_replace_all(x, "[^A-Z0-9 ]", " ")
  x <- stringr::str_squish(x)
  x <- stringr::str_remove(x, "\\s+SCHOOL$")
  x
}

# Map final_type (lowercase tokens in the CSV) to the human-readable labels
# the rest of the app uses for Type.
final_type_to_label <- function(x) {
  dplyr::case_when(
    x == "elementary"        ~ "Elementary",
    x == "middle"            ~ "Middle",
    x == "high"              ~ "High School",
    x == "elementary_middle" ~ "Elementary + Middle",
    x == "alternative"       ~ "Alternative",
    TRUE                     ~ NA_character_
  )
}

inferred_school_types <- read_csv("inferred_school_types_final.csv",
                                  show_col_types = FALSE) %>%
  mutate(
    SchlID_key    = pad_schlid(SchlID),
    School_inferred = stringr::str_squish(School),
    Type_inferred = final_type_to_label(final_type)
  ) %>%
  filter(!is.na(Type_inferred), !is.na(SchlID_key), SchlID_key != "000000") %>%
  distinct(SchlID_key, .keep_all = TRUE) %>%
  select(SchlID_key, School_inferred, Type_inferred)

# Attach Type_inferred + School_inferred to school_composition.
# school_composition's SchlID = Dist (3 digits) concatenated with Schl (3 digits).
school_composition <- school_composition %>%
  mutate(
    SchlID_key = paste0(
      stringr::str_pad(stringr::str_squish(as.character(Dist)), 3, "left", "0"),
      stringr::str_pad(stringr::str_squish(as.character(Schl)), 3, "left", "0")
    )
  ) %>%
  left_join(inferred_school_types, by = "SchlID_key") %>%
  select(-SchlID_key)

# Attach Type_inferred + School_inferred to school_existence.
# school_existence's SchlID = Schl_ID (already 6 digits, but pad defensively).
school_existence <- school_existence %>%
  mutate(SchlID_key = pad_schlid(Schl_ID)) %>%
  left_join(inferred_school_types, by = "SchlID_key") %>%
  select(-SchlID_key)

# =========================
# 1b. LOAD CURATED FINAL TYPES (source of truth for visualization)
# =========================
# school_existence_with_cleaned_types.xlsx is a CURATED file the user manually
# edited: it carries Type_raw / Type_pipeline / Type_inferred plus a hand-
# verified `type_final` column. We treat this file as read-only input and use
# `type_final` as the canonical school Type everywhere downstream
# (visualizations, filters, panels). The earlier Type / Type_inferred /
# Type_raw columns are kept for transparency and for the comparison sheets.
curated_path <- "school_existence_with_cleaned_types.xlsx"
if (!file.exists(curated_path)) {
  warning(curated_path, " not found — Type_final will be NA and Type will fall ",
          "back to the pipeline value.")
  curated_final_types <- tibble::tibble(
    SchlID_key = character(0),
    Type_final = character(0)
  )
} else {
  curated_final_types <- read_excel(curated_path) %>%
    mutate(
      SchlID_key = pad_schlid(Schl_ID),
      Type_final = stringr::str_squish(as.character(type_final))
    ) %>%
    filter(!is.na(SchlID_key), nzchar(SchlID_key)) %>%
    distinct(SchlID_key, .keep_all = TRUE) %>%
    select(SchlID_key, Type_final)
  message("Loaded curated type_final for ", nrow(curated_final_types), " schools.")
}

# ---- Curated closure status (used by the District Summary Table) ----
# The same curated workbook also carries hand-maintained `closed` / `end_year`
# columns. The District Summary Table reads those directly, so edits made in
# school_existence_with_cleaned_types.xlsx drive that tab without any code
# change. They are pulled in under distinct names (Closed_curated /
# End_year_curated) so the pipeline's own closed/end_year columns stay intact
# for every other tab.
if (!file.exists(curated_path)) {
  curated_closure_status <- tibble::tibble(
    SchlID_key       = character(0),
    Closed_curated   = logical(0),
    End_year_curated = integer(0)
  )
} else {
  curated_closure_status <- read_excel(curated_path) %>%
    mutate(
      SchlID_key       = pad_schlid(Schl_ID),
      Closed_curated   = as.logical(closed),
      End_year_curated = suppressWarnings(as.integer(end_year))
    ) %>%
    filter(!is.na(SchlID_key), nzchar(SchlID_key)) %>%
    distinct(SchlID_key, .keep_all = TRUE) %>%
    select(SchlID_key, Closed_curated, End_year_curated)
  message("Loaded curated closure status: ",
          sum(curated_closure_status$Closed_curated, na.rm = TRUE),
          " schools marked closed across ",
          nrow(curated_closure_status), " rows.")
}

# Attach Type_final + curated closure status to school_existence (by Schl_ID).
school_existence <- school_existence %>%
  mutate(SchlID_key = pad_schlid(Schl_ID)) %>%
  left_join(curated_final_types,    by = "SchlID_key") %>%
  left_join(curated_closure_status, by = "SchlID_key") %>%
  select(-SchlID_key)

# Attach Type_final to school_composition (by Dist + Schl -> 6-char SchlID).
school_composition <- school_composition %>%
  mutate(
    SchlID_key = paste0(
      stringr::str_pad(stringr::str_squish(as.character(Dist)), 3, "left", "0"),
      stringr::str_pad(stringr::str_squish(as.character(Schl)), 3, "left", "0")
    )
  ) %>%
  left_join(curated_final_types, by = "SchlID_key") %>%
  select(-SchlID_key)
# =========================
# 2. HELPER FUNCTIONS
# =========================
clean_school_status <- function(df) {
  if (!"Type_inferred"   %in% names(df)) df$Type_inferred   <- NA_character_
  if (!"Type_raw"        %in% names(df)) df$Type_raw        <- NA_character_
  if (!"Type_final"      %in% names(df)) df$Type_final      <- NA_character_
  if (!"School_inferred" %in% names(df)) df$School_inferred <- NA_character_

  # Curated closure columns fall back to the pipeline values when the curated
  # workbook is absent, so the District Summary Table still renders.
  if (!"Closed_curated"   %in% names(df)) df$Closed_curated   <- df$closed
  if (!"End_year_curated" %in% names(df)) df$End_year_curated <- df$end_year

  df %>%
    mutate(across(where(is.character), stringr::str_squish)) %>%
    mutate(
      Schl_ID = as.character(Schl_ID),
      District = str_remove(District, " County Schools$| Schools$| School District$"),
      District = str_squish(District),
      School = str_squish(School),
      School_inferred = str_squish(School_inferred),
      Type = str_squish(Type),
      Type_raw = str_squish(Type_raw),
      Type_inferred = str_squish(Type_inferred),
      Type_final = str_squish(Type_final),
      start_year = as.integer(start_year),
      end_year = as.integer(end_year),
      flipped = as.logical(flipped),
      closed = as.logical(closed),
      Closed_curated = as.logical(Closed_curated),
      End_year_curated = as.integer(End_year_curated)
    )
}

clean_district_panel <- function(df) {
  df %>%
    mutate(across(where(is.character), stringr::str_squish)) %>%
    rename(enrollment = Enrollment) %>%
    mutate(
      Year = as.integer(Year),
      District = str_remove(District, " County Schools$| Schools$| School District$"),
      District = str_squish(District)
    )
}

build_district_panel <- function(district_enr, school_status) {
  district_cons_cross <- school_status %>%
    filter(closed, !is.na(end_year)) %>%
    group_by(District) %>%
    summarise(
      first_cons_year = min(end_year, na.rm = TRUE),
      last_cons_year = max(end_year, na.rm = TRUE),
      n_closed = n(),
      .groups = "drop"
    )
  
  district_enr %>%
    left_join(district_cons_cross, by = "District") %>%
    mutate(
      event_time_cons_year = Year - first_cons_year,
      event_time_pre_year = Year - (first_cons_year - 1)
    )
}

build_map_data <- function(district_panel, district_shapes) {
  district_summary <- district_panel %>%
    group_by(District) %>%
    arrange(Year, .by_group = TRUE) %>%
    summarise(
      enrollment_first = enrollment[Year == min(Year, na.rm = TRUE)][1],
      enrollment_last = enrollment[Year == max(Year, na.rm = TRUE)][1],
      first_cons_year = first(first_cons_year),
      last_cons_year = first(last_cons_year),
      n_closed = first(n_closed),
      .groups = "drop"
    ) %>%
    mutate(
      total_change = enrollment_last - enrollment_first,
      pct_change = 100 * total_change / enrollment_first,
      n_closed = tidyr::replace_na(n_closed, 0)
    )
  
  district_shapes %>%
    mutate(
      District = str_remove(NAME, " County School District$| County Schools$| Schools$| School District$"),
      District = str_squish(District)
    ) %>%
    left_join(district_summary, by = "District")
}

clean_school_composition <- function(df) {
  names(df) <- names(df) %>%
    stringr::str_replace_all("\\r\\n", " ") %>%
    stringr::str_squish()

  if (!"Type_inferred"   %in% names(df)) df$Type_inferred   <- NA_character_
  if (!"Type_raw"        %in% names(df)) df$Type_raw        <- NA_character_
  if (!"Type_final"      %in% names(df)) df$Type_final      <- NA_character_
  if (!"School_inferred" %in% names(df)) df$School_inferred <- NA_character_

  df %>%
    mutate(across(where(is.character), stringr::str_squish)) %>%
    mutate(
      Year = as.integer(Year),
      Schl = as.character(Schl),
      District = str_remove(District, " County Schools$| Schools$| School District$"),
      District = str_squish(District),
      School = str_squish(School),
      School_inferred = str_squish(School_inferred),
      Type = str_squish(Type),
      Type_raw = str_squish(Type_raw),
      Type_inferred = str_squish(Type_inferred),
      Type_final = str_squish(Type_final),
      headcount = readr::parse_number(`Total Headcount`)
    ) %>%
    select(Year, District, Schl, School, School_inferred,
           Type_raw, Type, Type_inferred, Type_final, headcount)
}

build_pre_post_plot_data <- function(district_panel_df, offset = 0) {
  district_panel_df %>%
    filter(!is.na(first_cons_year)) %>%
    mutate(
      threshold = first_cons_year + offset,
      period = ifelse(Year <= threshold, "pre", "post"),
      facet_label = paste0(District, " (c=", first_cons_year, ")")
    )
}

build_closure_year_map_data <- function(school_status, district_shapes, year_min = NULL, year_max = NULL) {
  
  shape_df <- district_shapes %>%
    mutate(
      District = stringr::str_remove(NAME, " County School District$| County Schools$| Schools$| School District$"),
      District = stringr::str_squish(District)
    )
  
  closure_counts <- school_status %>%
    filter(closed, !is.na(end_year)) %>%
    group_by(District, Year = end_year) %>%
    summarise(
      n_closed_that_year = n(),
      .groups = "drop"
    )
  
  years_all <- sort(unique(school_status$end_year[!is.na(school_status$end_year)]))
  
  if (!is.null(year_min)) years_all <- years_all[years_all >= year_min]
  if (!is.null(year_max)) years_all <- years_all[years_all <= year_max]
  
  district_year_grid <- tidyr::expand_grid(
    District = unique(shape_df$District),
    Year = years_all
  )
  
  closure_counts_full <- district_year_grid %>%
    left_join(closure_counts, by = c("District", "Year")) %>%
    mutate(
      n_closed_that_year = tidyr::replace_na(n_closed_that_year, 0)
    )
  
  shape_df %>%
    left_join(closure_counts_full, by = "District")
}

build_cumulative_closure_map_data <- function(school_status, district_shapes, year_min = NULL, year_max = NULL) {
  
  shape_df <- district_shapes %>%
    mutate(
      District = stringr::str_remove(NAME, " County School District$| County Schools$| Schools$| School District$"),
      District = stringr::str_squish(District)
    )
  
  years_all <- sort(unique(school_status$end_year[!is.na(school_status$end_year)]))
  
  if (!is.null(year_min)) years_all <- years_all[years_all >= year_min]
  if (!is.null(year_max)) years_all <- years_all[years_all <= year_max]
  
  district_year_grid <- tidyr::expand_grid(
    District = unique(shape_df$District),
    Year = years_all
  )
  
  cumulative_counts <- district_year_grid %>%
    rowwise() %>%
    mutate(
      cumulative_closed = sum(
        school_status$District == District &
          school_status$closed == TRUE &
          !is.na(school_status$end_year) &
          school_status$end_year <= Year,
        na.rm = TRUE
      )
    ) %>%
    ungroup()
  
  shape_df %>%
    left_join(cumulative_counts, by = "District")
}

build_type_specific_panel <- function(school_comp_clean, school_status, selected_types) {
  
  if (is.null(selected_types) || "All" %in% selected_types) {
    
    type_enr <- school_comp_clean %>%
      group_by(Year, District) %>%
      summarise(
        enrollment = sum(headcount, na.rm = TRUE),
        .groups = "drop"
      )
    
    type_status <- school_status
    
  } else {
    
    type_enr <- school_comp_clean %>%
      filter(Type %in% selected_types) %>%
      group_by(Year, District) %>%
      summarise(
        enrollment = sum(headcount, na.rm = TRUE),
        .groups = "drop"
      )
    
    type_status <- school_status %>%
      filter(Type %in% selected_types)
  }
  
  build_district_panel(type_enr, type_status)
}

build_selected_type_panel <- function(school_comp_clean, school_status, selected_types) {
  
  if (is.null(selected_types) || "All" %in% selected_types) {
    comp_df <- school_comp_clean
    status_df <- school_status
  } else {
    comp_df <- school_comp_clean %>%
      filter(Type %in% selected_types)
    
    status_df <- school_status %>%
      filter(Type %in% selected_types)
  }
  
  type_enr <- comp_df %>%
    group_by(Year, District) %>%
    summarise(
      enrollment = sum(headcount, na.rm = TRUE),
      .groups = "drop"
    )
  
  build_district_panel(type_enr, status_df)
}
# =========================
# 3. BUILD CLEAN OBJECTS
# =========================


# K-8s?
# Identify schools serving both elementary and middle grades
elem_middle_schools <- school_composition %>%
  mutate(
    grade3 = suppressWarnings(readr::parse_number(`Grade 3`)),
    grade8 = suppressWarnings(readr::parse_number(`Grade 8`)),
    Schl = as.character(Schl),
    District = stringr::str_squish(District)
  ) %>%
  filter(
    !is.na(grade3), grade3 > 0,
    !is.na(grade8), grade8 > 0
  ) %>%
  distinct(Schl, District)


school_status <- clean_school_status(school_existence)
district_enr <- clean_district_panel(district_enrollment_panel)
school_comp_clean <- clean_school_composition(school_composition)
#district_panel <- build_district_panel(district_enr, school_status)


standardize_type <- function(type, school_name) {
  type_lower <- str_to_lower(type)
  name_lower <- str_to_lower(school_name)
  
  case_when(
    str_detect(type_lower, "alternative") ~ "Alternative",
    str_detect(type_lower, "elementary|primary") ~ "Elementary",
    str_detect(type_lower, "middle") ~ "Middle",
    str_detect(type_lower, "high|secondary") ~ "High School",
    
    str_detect(name_lower, "alternative") ~ "Alternative",
    str_detect(name_lower, "elementary|primary") ~ "Elementary",
    str_detect(name_lower, "middle") ~ "Middle",
    str_detect(name_lower, "high") ~ "High School",
    
    TRUE ~ type
  )
}

school_comp_clean <- school_comp_clean %>%
  mutate(Type = standardize_type(Type, School))


# Recode school_comp_clean
school_comp_clean <- school_comp_clean %>%
  mutate(
    Schl = as.character(Schl),
    District = stringr::str_squish(District)
  ) %>%
  left_join(
    elem_middle_schools %>%
      mutate(elem_middle = TRUE),
    by = c("Schl", "District")
  ) %>%
  mutate(
    Type = case_when(
      elem_middle == TRUE ~ "Elementary + Middle",
      TRUE ~ Type
    )
  ) %>%
  select(-elem_middle)

school_status <- school_status %>%
  mutate(Type = standardize_type(Type, School))

# Recode school_status
school_status <- school_status %>%
  mutate(
    Schl_ID = as.character(Schl_ID),
    District = stringr::str_squish(District),
    
    # keep only last 3 characters
    school_match_id = stringr::str_sub(Schl_ID, -3, -1)
  ) %>%
  left_join(
    elem_middle_schools %>%
      mutate(
        Schl = as.character(Schl),
        District = stringr::str_squish(District),
        
        # keep only last 3 characters
        school_match_id = stringr::str_sub(Schl, -3, -1),
        
        elem_middle = TRUE
      ) %>%
      select(District, school_match_id, elem_middle),
    
    by = c("District", "school_match_id")
  ) %>%
  mutate(
    Type = case_when(
      elem_middle == TRUE ~ "Elementary + Middle",
      TRUE ~ Type
    )
  ) %>%
  select(-elem_middle, -school_match_id)

# =========================
# 3a. COMPARE THREE TYPE SOURCES SIDE-BY-SIDE
# =========================
# Type_raw      = original Type from school_existence.xlsx / school_composition.xlsx
# Type          = result of the existing pipeline
#                 (school_year_enrollment_types.csv + standardize_type + elem_middle override)
# Type_inferred = final_type from inferred_school_types_final.csv

classify_match <- function(a, b, c) {
  # all-three agreement, any pairwise agreement, or all three different
  has_a <- !is.na(a); has_b <- !is.na(b); has_c <- !is.na(c)
  dplyr::case_when(
    has_a & has_b & has_c & a == b & b == c ~ "all_three_agree",
    has_a & has_b & has_c & a != b & a != c & b != c ~ "all_three_differ",
    !has_c                              ~ "no_inferred_match",
    !has_b                              ~ "no_pipeline_type",
    !has_a                              ~ "no_raw_type",
    a == b & b != c                     ~ "raw=pipeline; inferred differs",
    a == c & b != c                     ~ "raw=inferred; pipeline differs",
    b == c & a != b                     ~ "pipeline=inferred; raw differs",
    TRUE                                ~ "disagree"
  )
}

# --- Name similarity helper for verifying the SchlID merge ---
# Token-Jaccard similarity on normalized names: shared tokens / total unique tokens.
# 1.00 = identical after normalization, 0.00 = no tokens shared, NA = either name missing.
name_similarity <- function(a, b) {
  out <- rep(NA_real_, length(a))
  for (i in seq_along(a)) {
    if (is.na(a[i]) || is.na(b[i])) next
    ta <- strsplit(normalize_school_name(a[i]), " ", fixed = TRUE)[[1]]
    tb <- strsplit(normalize_school_name(b[i]), " ", fixed = TRUE)[[1]]
    ta <- ta[nchar(ta) > 0]; tb <- tb[nchar(tb) > 0]
    if (!length(ta) && !length(tb)) { out[i] <- 1; next }
    if (!length(ta) ||  !length(tb)) { out[i] <- 0; next }
    inter <- length(intersect(ta, tb))
    uni   <- length(union(ta, tb))
    out[i] <- if (uni == 0) NA_real_ else inter / uni
  }
  out
}

merge_check <- function(sim) {
  dplyr::case_when(
    is.na(sim)  ~ "no_inferred_match",
    sim >= 0.80 ~ "ok",
    sim >= 0.40 ~ "minor_diff",        # name formatting / suffix differences
    TRUE        ~ "likely_wrong_match" # names look like different schools
  )
}

# school_status: one row per school in the existence/status file
type_comparison_status <- school_status %>%
  mutate(
    Type_raw         = str_squish(Type_raw),
    Type             = str_squish(Type),
    Type_inferred    = str_squish(Type_inferred),
    Type_final       = str_squish(Type_final),
    School_inferred  = str_squish(School_inferred),
    name_similarity  = name_similarity(School, School_inferred),
    merge_check      = merge_check(name_similarity),
    type_match       = classify_match(Type_raw, Type, Type_inferred)
  ) %>%
  select(District, Schl_ID, School, School_inferred,
         name_similarity, merge_check,
         Type_raw, Type_pipeline = Type, Type_inferred, Type_final,
         type_match)

# school_comp_clean: collapse the year panel to one row per (Schl, School)
type_comparison_comp <- school_comp_clean %>%
  mutate(
    Type_raw         = str_squish(Type_raw),
    Type             = str_squish(Type),
    Type_inferred    = str_squish(Type_inferred),
    Type_final       = str_squish(Type_final),
    School_inferred  = str_squish(School_inferred)
  ) %>%
  distinct(District, Schl, School, School_inferred,
           Type_raw, Type, Type_inferred, Type_final) %>%
  mutate(
    name_similarity = name_similarity(School, School_inferred),
    merge_check     = merge_check(name_similarity),
    type_match      = classify_match(Type_raw, Type, Type_inferred)
  ) %>%
  rename(Type_pipeline = Type)

# Quick console summary
message("Three-source type match — school_status:")
print(table(type_comparison_status$type_match, useNA = "ifany"))
message("Three-source type match — school_comp_clean:")
print(table(type_comparison_comp$type_match, useNA = "ifany"))

message("SchlID merge check (name similarity) — school_status:")
print(table(type_comparison_status$merge_check, useNA = "ifany"))
message("SchlID merge check (name similarity) — school_comp_clean:")
print(table(type_comparison_comp$merge_check, useNA = "ifany"))

# -------------------------------------------------------------
# Write the comparison to an Excel workbook for manual review.
# Sheets:
#   school_status_all      — all schools in school_status with the 3 type cols
#   school_comp_all        — distinct (Schl, School) rows from school_comp_clean
#   school_status_disagree — only rows where the 3 sources don't unanimously agree
#   school_comp_disagree   — same, for school_comp_clean
#   summary_status / summary_comp — counts by type_match
#
# NOTE: written with explicit dplyr:: calls (no %>%) so this block still runs
# even if magrittr/dplyr aren't attached in the current session.
# -------------------------------------------------------------
if (!requireNamespace("openxlsx", quietly = TRUE)) {
  install.packages("openxlsx", repos = "https://cloud.r-project.org")
}
# Defensive: make sure the pipe is available anywhere it's still used.
suppressMessages(suppressWarnings(library(magrittr)))

type_check_path <- "type_source_comparison.xlsx"

school_status_all      <- dplyr::arrange(type_comparison_status, District, School)
school_comp_all        <- dplyr::arrange(type_comparison_comp,   District, School)

school_status_disagree <- dplyr::arrange(
  dplyr::filter(type_comparison_status, type_match != "all_three_agree"),
  type_match, District, School
)
school_comp_disagree   <- dplyr::arrange(
  dplyr::filter(type_comparison_comp,   type_match != "all_three_agree"),
  type_match, District, School
)

summary_status <- dplyr::arrange(
  dplyr::count(type_comparison_status, type_match, name = "n"),
  dplyr::desc(n)
)
summary_comp   <- dplyr::arrange(
  dplyr::count(type_comparison_comp,   type_match, name = "n"),
  dplyr::desc(n)
)

# Merge-quality sheets: SchlID matched but school names look different.
# Sorted worst-first so the suspect rows (likely school-code reuse) are on top.
merge_check_status <- dplyr::arrange(
  dplyr::filter(type_comparison_status, merge_check %in% c("minor_diff", "likely_wrong_match")),
  name_similarity, District, School
)
merge_check_comp <- dplyr::arrange(
  dplyr::filter(type_comparison_comp,   merge_check %in% c("minor_diff", "likely_wrong_match")),
  name_similarity, District, School
)

merge_check_summary <- dplyr::bind_rows(
  dplyr::mutate(dplyr::count(type_comparison_status, merge_check, name = "n"),
                source = "school_status"),
  dplyr::mutate(dplyr::count(type_comparison_comp,   merge_check, name = "n"),
                source = "school_comp_clean")
)
merge_check_summary <- merge_check_summary[, c("source", "merge_check", "n")]

openxlsx::write.xlsx(
  list(
    school_status_all      = school_status_all,
    school_comp_all        = school_comp_all,
    school_status_disagree = school_status_disagree,
    school_comp_disagree   = school_comp_disagree,
    summary_status         = summary_status,
    summary_comp           = summary_comp,
    merge_check_status     = merge_check_status,
    merge_check_comp       = merge_check_comp,
    merge_check_summary    = merge_check_summary
  ),
  file = type_check_path,
  overwrite = TRUE
)

message("Wrote three-source type comparison to: ", normalizePath(type_check_path))

# =========================
# 3b. PER-SCHOOL CSV: types + status (from school_comp_clean joined to school_status)
# =========================
# One row per school in the enrollment file. Carries all three Type columns and
# the status fields (start/end year, closed, flipped, news URLs) from school_status.
# Status is joined on District + the last 3 chars of the school code, which is
# the same matching rule already used elsewhere in this script (Schl in
# school_composition is the 3-digit local code; Schl_ID in school_status is
# the 6-digit district+local code).

# Distinct school-level rows from school_comp_clean
schools_from_comp <- dplyr::group_by(school_comp_clean, District, Schl)
schools_from_comp <- dplyr::summarise(
  schools_from_comp,
  School                = dplyr::first(School),
  Type_raw              = dplyr::first(Type_raw),
  Type_pipeline         = dplyr::first(Type),
  Type_inferred         = dplyr::first(Type_inferred),
  n_years_with_data     = dplyr::n_distinct(Year),
  first_year_with_data  = suppressWarnings(min(Year, na.rm = TRUE)),
  last_year_with_data   = suppressWarnings(max(Year, na.rm = TRUE)),
  total_headcount_last  = sum(headcount[Year == suppressWarnings(max(Year, na.rm = TRUE))],
                              na.rm = TRUE),
  .groups = "drop"
)

# Status side (the columns we want to merge in)
status_cols <- intersect(
  c("Schl_ID", "start_year", "end_year", "flipped", "closed",
    "Consolidation_Summary", "Closure_News_URL", "Closure_News_URL2"),
  names(school_status)
)
status_for_join <- dplyr::mutate(
  school_status,
  school_match_id = stringr::str_sub(as.character(Schl_ID), -3, -1)
)
status_for_join <- dplyr::select(status_for_join,
                                 dplyr::all_of(c("District", "school_match_id", status_cols)))

schools_with_types_and_status <- dplyr::mutate(
  schools_from_comp,
  school_match_id = stringr::str_sub(as.character(Schl), -3, -1)
)
schools_with_types_and_status <- dplyr::left_join(
  schools_with_types_and_status,
  status_for_join,
  by = c("District", "school_match_id")
)
schools_with_types_and_status <- dplyr::select(schools_with_types_and_status,
                                               -school_match_id)
schools_with_types_and_status <- dplyr::arrange(schools_with_types_and_status,
                                                District, School)

schools_csv_path <- "schools_with_types_and_status.csv"
write.csv(schools_with_types_and_status, schools_csv_path, row.names = FALSE, na = "")
message("Wrote per-school types + status CSV to: ", normalizePath(schools_csv_path))

# =========================
# 3c. MERGED school_existence.xlsx with cleaned types
# =========================
# Take the cleaned school_status (which already carries Type_raw / Type / Type_inferred
# along with every original existence column) and write it back to an .xlsx with
# the three Type columns up front. Saved to a NEW filename so the original
# school_existence.xlsx is not overwritten — rename it if you want to swap it in.
school_existence_merged <- dplyr::rename(school_status, Type_pipeline = Type)

# Put the three type columns right after School for easy scanning
front_cols <- intersect(
  c("Schl_ID", "District", "School", "Type_raw", "Type_pipeline", "Type_inferred"),
  names(school_existence_merged)
)
other_cols <- setdiff(names(school_existence_merged), front_cols)
school_existence_merged <- school_existence_merged[, c(front_cols, other_cols)]

# Auto-write disabled: school_existence_with_cleaned_types.xlsx is now the
# CURATED INPUT (it carries the user's hand-verified `type_final` column) and
# must not be overwritten by the script. If you want an updated snapshot of
# the pipeline's view, write to a different filename, e.g.:
# openxlsx::write.xlsx(school_existence_merged,
#                      "school_existence_pipeline_types.xlsx",
#                      overwrite = TRUE)


# =========================
# 3d. OVERRIDE Type WITH CURATED type_final
# =========================
# This is the canonical Type column from this point on. Every downstream
# visualization, filter, panel, and map reads `Type`, so by replacing it here
# (after the comparison sheets and CSV are written) we ensure the dashboard
# shows the user's curated types — falling back to the pipeline value only if
# Type_final is missing for a school.
apply_type_final <- function(df) {
  if (!"Type_final" %in% names(df)) return(df)
  has_final     <- !is.na(df$Type_final) & nzchar(df$Type_final)
  df$Type_final_source <- ifelse(has_final, "curated", "pipeline_fallback")
  df$Type <- ifelse(has_final, df$Type_final, df$Type)
  df
}

school_status    <- apply_type_final(school_status)
school_comp_clean <- apply_type_final(school_comp_clean)

message(sprintf(
  "Type_final applied — school_status: %d curated, %d pipeline fallback",
  sum(school_status$Type_final_source == "curated",            na.rm = TRUE),
  sum(school_status$Type_final_source == "pipeline_fallback",  na.rm = TRUE)
))
message(sprintf(
  "Type_final applied — school_comp_clean: %d curated, %d pipeline fallback",
  sum(school_comp_clean$Type_final_source == "curated",           na.rm = TRUE),
  sum(school_comp_clean$Type_final_source == "pipeline_fallback", na.rm = TRUE)
))


district_panel <- build_district_panel(district_enr, school_status) %>%
  left_join(census, by = c("District", "Year"))

district_shapes <- sf::st_read("district_shapes/tl_2021_54_unsd.shp", quiet = TRUE)
district_shapes <- sf::st_transform(district_shapes, 4326)

# =========================
# 3.5 HOPE SCHOLARSHIP DATA
# =========================
# Recipient counts by county from the Hope Scholarship annual reports
# (SY 2022-23, 2023-24, 2024-25). The workbook has a title block above the
# header row, so we locate the row whose first cell is "County" rather than
# assuming a fixed skip. Optional: if the file is absent the tab renders an
# explanatory message instead of a map, so a fresh clone still runs.
hope_path <- "Hope Recipients by County 2022-2025.xlsx"

hope_recipients <- local({
  if (!file.exists(hope_path)) {
    warning(hope_path, " not found - the Hope Scholarship tab will be empty.")
    return(tibble::tibble(
      District = character(0), hope_2023 = integer(0),
      hope_2024 = integer(0),  hope_2025 = integer(0)
    ))
  }

  raw <- read_excel(hope_path, col_names = FALSE)
  names(raw) <- paste0("V", seq_len(ncol(raw)))

  hdr <- which(stringr::str_squish(as.character(raw$V1)) == "County")[1]
  if (is.na(hdr)) {
    warning("Could not find the 'County' header row in ", hope_path,
            " - the Hope Scholarship tab will be empty.")
    return(tibble::tibble(
      District = character(0), hope_2023 = integer(0),
      hope_2024 = integer(0),  hope_2025 = integer(0)
    ))
  }

  raw[(hdr + 1):nrow(raw), 1:4] %>%
    setNames(c("District", "hope_2023", "hope_2024", "hope_2025")) %>%
    mutate(District = stringr::str_squish(as.character(District))) %>%
    filter(
      !is.na(District), nzchar(District),
      !stringr::str_detect(District, stringr::regex("^(total|source)", ignore_case = TRUE))
    ) %>%
    mutate(across(
      c(hope_2023, hope_2024, hope_2025),
      ~ tidyr::replace_na(suppressWarnings(as.integer(.x)), 0L)
    ))
})

message("Loaded Hope Scholarship recipients for ", nrow(hope_recipients),
        " counties; SY 24-25 statewide total = ",
        format(sum(hope_recipients$hope_2025), big.mark = ","), ".")

# Latest school-age population from the PEP series, used as the rate denominator.
hope_pop_year <- suppressWarnings(max(school_age_pep_raw$year, na.rm = TRUE))
if (!is.finite(hope_pop_year)) hope_pop_year <- NA_integer_

hope_school_age <- if (is.na(hope_pop_year)) {
  tibble::tibble(District = character(0), school_age_pop = numeric(0))
} else {
  school_age_pep_raw %>%
    filter(year == hope_pop_year) %>%
    transmute(
      District       = stringr::str_squish(as.character(county)),
      school_age_pop = as.numeric(school_age_pop_pep)
    ) %>%
    distinct(District, .keep_all = TRUE)
}

# First school year in which Hope money was disbursed. Closures with an end_year
# at or after this are "post-Hope" for the dot coloring.
HOPE_START_YEAR <- 2023L

# Curated closure status is authoritative where present; fall back to the
# pipeline columns so the tab still works without the curated workbook.
hope_school_status <- school_status %>%
  mutate(
    is_closed  = dplyr::coalesce(Closed_curated,   closed),
    close_year = dplyr::coalesce(End_year_curated, end_year)
  )

# County-level table driving the choropleth. Built off district_shapes so every
# mapped county has a row even if it is missing from the Hope workbook.
hope_county_base <- district_shapes %>%
  sf::st_drop_geometry() %>%
  transmute(
    District = stringr::str_squish(stringr::str_remove(
      NAME, " County School District$| County Schools$| Schools$| School District$"
    ))
  ) %>%
  distinct(District) %>%
  left_join(hope_recipients, by = "District") %>%
  left_join(hope_school_age, by = "District") %>%
  mutate(
    across(c(hope_2023, hope_2024, hope_2025), ~ tidyr::replace_na(.x, 0L)),
    # One rate per school year so the year selector can shade any of the three.
    # The denominator is the same PEP school-age count in all three years, so
    # these are comparable across years by construction.
    no_denom   = is.na(school_age_pop) | school_age_pop == 0,
    rate_2023  = ifelse(no_denom, NA_real_, 100 * hope_2023 / school_age_pop),
    rate_2024  = ifelse(no_denom, NA_real_, 100 * hope_2024 / school_age_pop),
    rate_2025  = ifelse(no_denom, NA_real_, 100 * hope_2025 / school_age_pop),
    growth     = hope_2025 - hope_2023,
    growth_pct = ifelse(hope_2023 == 0, NA_real_,
                        100 * (hope_2025 - hope_2023) / hope_2023)
  ) %>%
  select(-no_denom)

# Warn loudly if the Hope workbook and the shapefile disagree on county names,
# since a silent mismatch would show up as a blank county on the map.
local({
  unmatched <- setdiff(hope_recipients$District, hope_county_base$District)
  if (length(unmatched)) {
    warning("Hope workbook counties not matched to a district shape: ",
            paste(unmatched, collapse = ", "))
  }
})

# ---- Closure dots -------------------------------------------------------
# There is no latitude/longitude anywhere in the source data - school_directory
# carries street addresses but nothing geocoded. Each dot is therefore placed at
# a random point INSIDE its own county polygon: the per-county count and the
# county assignment are exact, the position within the county is not. The seed
# is fixed so the scatter is identical on every run.
hope_dots <- local({
  closed_schools <- hope_school_status %>%
    filter(is_closed %in% TRUE) %>%
    mutate(dot_era = ifelse(!is.na(close_year) & close_year >= HOPE_START_YEAR,
                            "post", "pre"))

  # Board-approved closures that have not taken effect yet: not flagged closed,
  # but carrying a consolidation note.
  pending_schools <- hope_school_status %>%
    filter(!(is_closed %in% TRUE),
           !is.na(Consolidation_Summary), nzchar(Consolidation_Summary)) %>%
    mutate(dot_era = "pending", close_year = NA_integer_)

  dots <- bind_rows(closed_schools, pending_schools)
  if (nrow(dots) == 0) return(dots[0, ] %>% mutate(lon = numeric(0), lat = numeric(0)))

  shapes_named <- district_shapes %>%
    mutate(District = stringr::str_squish(stringr::str_remove(
      NAME, " County School District$| County Schools$| Schools$| School District$"
    )))

  dots <- dots %>% filter(District %in% shapes_named$District)

  set.seed(20260728)
  placed <- lapply(split(dots, dots$District), function(grp) {
    poly <- shapes_named[shapes_named$District == grp$District[1], ]
    pts  <- suppressMessages(
      sf::st_sample(sf::st_geometry(poly), size = nrow(grp), type = "random")
    )
    # st_sample can return fewer points than requested; top up from the centroid.
    coords <- sf::st_coordinates(pts)
    if (nrow(coords) < nrow(grp)) {
      ctr <- sf::st_coordinates(sf::st_point_on_surface(sf::st_geometry(poly)))
      need <- nrow(grp) - nrow(coords)
      coords <- rbind(coords[, 1:2, drop = FALSE],
                      cbind(X = rep(ctr[1, 1], need), Y = rep(ctr[1, 2], need)))
    }
    grp$lon <- coords[seq_len(nrow(grp)), 1]
    grp$lat <- coords[seq_len(nrow(grp)), 2]
    grp
  })

  bind_rows(placed) %>%
    mutate(
      dot_label = ifelse(is.na(close_year),
                         "Closure approved, not yet effective",
                         paste0("Last year of operation: ", close_year)),
      dot_note  = ifelse(is.na(Consolidation_Summary), "",
                         stringr::str_squish(sub(" \\| .*$", "", Consolidation_Summary)))
    )
})

message("Hope tab closure dots: ", sum(hope_dots$dot_era != "pending"),
        " closed, ", sum(hope_dots$dot_era == "pending"), " pending.")

# Every dot is drawn in this one color. dot_era is still carried on the data so
# the "closures since Hope" filter and the Status column in the school table
# below the map keep working; it just no longer drives the fill.
HOPE_DOT_COLOR <- "#c0392b"

HOPE_DOT_LABELS <- c(
  pre     = "Closed before Hope (through 2022)",
  post    = paste0("Closed since Hope (", HOPE_START_YEAR, "+)"),
  pending = "Approved, closing soon"
)

# The choropleth is a measure x year pair: the measure picks a column prefix,
# the year picks the suffix. Growth and closure counts are still computed in
# hope_county_base and shown in the county table; they are not shading options.
HOPE_MEASURES <- list(
  "rate" = list(label    = "Recipients per 100 school-age children",
                legend   = "Per 100\nschool-age",
                prefix   = "rate_",
                accuracy = 0.1),
  "hope" = list(label    = "Recipients, raw count",
                legend   = "Recipients",
                prefix   = "hope_",
                accuracy = 1)
)

# Display label -> column suffix. Hope pays out on a school year, so SY 2022-23
# is stored as 2023 (the year the school year ends), matching end_year elsewhere.
HOPE_YEARS <- c("SY 2022-23" = "2023",
                "SY 2023-24" = "2024",
                "SY 2024-25" = "2025")

# Color scale limits are fixed across all three years, computed once at startup
# rather than per render. This is the whole point of a shared scale: switching
# years must show the program growing, not re-normalize each year to look the
# same. Anchored at 0 so a pale county always means "few recipients".
HOPE_LIMITS <- lapply(HOPE_MEASURES, function(m) {
  cols <- paste0(m$prefix, HOPE_YEARS)
  c(0, max(unlist(hope_county_base[cols]), na.rm = TRUE))
})

message("Hope shared scale limits - rate: 0-", round(HOPE_LIMITS$rate[2], 2),
        " per 100 | count: 0-", HOPE_LIMITS$hope[2], " recipients.")

school_type_order <- c(
  "Elementary",
  "Elementary + Middle",
  "Middle",
  "High School",
  "Alternative"
)

school_type_choices <- unique(c(
  as.character(school_status$Type),
  as.character(school_comp_clean$Type)
))
school_type_choices <- school_type_choices[!is.na(school_type_choices)]
school_type_choices <- c(
  school_type_order[school_type_order %in% school_type_choices],
  sort(setdiff(school_type_choices, school_type_order))
)


#district_map_sf <- build_map_data(district_panel, district_shapes) %>%
#  mutate(
#    label_html = sprintf(
#      "<strong>%s</strong><br>Percent change: %.1f%%<br>Change in # Students: %s<br>Closed schools: %s",
#      District,
#      pct_change,
#      scales::comma(total_change),
#      n_closed
#    )
#  )



closure_map_df <- build_closure_year_map_data(
  school_status = school_status,
  district_shapes = district_shapes,
  year_min = min(district_panel$Year, na.rm = TRUE),
  year_max = max(district_panel$Year, na.rm = TRUE)
)



#closure_map_df$Year <- factor(closure_map_df$Year)

#ggplot(closure_map_df) +
#  geom_sf(aes(fill = n_closed_that_year), color = "gray50", linewidth = 0.15) +
#  facet_wrap(~Year, ncol = 5) +
#  scale_fill_gradient(
#    low = "#f7fbff",
#    high = "red3",
#    na.value = "#d9d9d9"
#  ) +
#  labs(
#    title = "Number of Schools Closed Within Each District by Year",
#    fill = "# Closed"
#  ) +
#  theme_void() +
#  theme(
###    strip.text = element_text(size = 9),
##    plot.title = element_text(size = 12, hjust = 0.5),
#    legend.position = "bottom"
#  )
# =========================
# 4. UI
# =========================
ui <- fluidPage(
  
  tags$head(
    tags$style(HTML("
    
    /* Inactive tabs */
    .nav-tabs > li > a {
      background-color: #eaf6ff;
      color: #003366;
      border: 1px solid #b3e0ff;
    }

    /* Active tab */
    .nav-tabs > li.active > a,
    .nav-tabs > li.active > a:focus,
    .nav-tabs > li.active > a:hover {
      background-color: #87ceeb;
      color: #003366;
      border: 1px solid #87ceeb;
      font-weight: 600;
    }

    /* Hover */
    .nav-tabs > li > a:hover {
      background-color: #cceeff;
    }

  "))
  ),
  
 # titlePanel("West Virginia School Closures & Enrollment Dashboard"),
  fluidRow(
    column(
      width = 12,
      div(
        style = "display: flex; align-items: center; gap: 15px;",
        
        img(
          src = "static/wv_flag.jpg",
          height = "50px",
          alt = "West Virginia state flag"
        ),
        
        h2("West Virginia School Consolidations",
           style = "margin: 0; font-weight: 600;")
      )
    )
  ),
  
  sidebarLayout(
    sidebarPanel(
      width = 3,

      # DESCRIPTION
      div(
        style = "background-color: #f7fbff; padding: 10px; border-radius: 6px; margin-bottom: 15px;",
        
        h4("About this Dashboard", style = "margin-top: 0;"),
        
        p(
          "This dashboard explores school closures and enrollment trends across West Virginia districts from 2011 to 2026. 
      It allows users to examine enrollment changes before and after closures, identify closure patterns, 
      and visualize both annual and cumulative closures across districts.",
          style = "font-size: 13px; margin-bottom: 5px;"
        ),
        
        p(
          "Use the filters below to explore specific districts, school grade levels, and time periods.",
          style = "font-size: 12px; color: #555; margin-top: 10px;"
        )
      ),
      
      hr(),
      # Filters
      selectInput(
        "district_filter",
        "District",
        choices = c("All", sort(unique(school_status$District))),
        selected = "All",
        multiple = TRUE
      ),
      
      selectInput(
        "school_type_filter",
        "School Grade Levels",
        choices = c("All", school_type_choices),
        selected = "All",
        multiple = TRUE
      ),
      
      sliderInput(
        "year_range",
        "Year range",
        min = min(district_panel$Year, na.rm = TRUE),
        max = max(district_panel$Year, na.rm = TRUE),
        value = c(
          min(district_panel$Year, na.rm = TRUE),
          max(district_panel$Year, na.rm = TRUE)
        ),
        step = 1,
        sep = ""
    ),
    
    hr(),
    
    # Footer / credits
    div(
      style = "font-size: 11px; color: #666; margin-top: 15px; line-height: 1.5;",
      
      HTML(
        'This dashboard is updated and maintained by 
      Jonas Xie, Tiffany Wu, and Christina Weiland at the 
      <a href="https://edpolicy.umich.edu/" target="_blank">
      University of Michigan&apos;s Education Policy Initiative
      </a>.
      <br><br>
      Please contact 
      <a href="mailto:weilandc@umich.edu">weilandc@umich.edu</a> 
      with any questions.'
      )
    )
    ),
    
    mainPanel(
      tabsetPanel(
         # =========================
          # LANDING PAGE
          # =========================
          tabPanel(
            "Welcome",
           
            br(),
           
            div(
              style = "text-align: center;",
             
              h2("West Virginia School Consolidation Dashboard"),
             
              p(
                "Explore school closures, consolidation timing, and enrollment trends across West Virginia districts from 2011-2026.",
                style = "font-size: 16px; color: #555;"
              ),
             
              br(),
             
              # GIF (served via the addResourcePath("static", www) prefix
              # registered at the top of this file)
              img(
                src   = "static/Weiland-wv-graphic-final.gif",
                width = "80%",
                alt   = "West Virginia school consolidation animation",
                style = "border-radius: 10px; box-shadow: 0px 0px 10px rgba(0,0,0,0.15);"
              ),
             
              br(), br(),
             
              p(
                "Use the tabs above to navigate maps, enrollment trends, and closure patterns.",
                style = "font-size: 14px; color: #777;"
              )
            )
          ),
         
        tabPanel(
          "District Summary Table",
          DTOutput("desc_table")
        ),
        tabPanel(
          "Total Enrollment Change Map",
          tags$iframe(
            src = "map_files/enrollment_change_map.html",
            style = "width: 100%; height: 700px; border: none;",
            seamless = NA
          )
        ),
        tabPanel(
          "Hope Scholarship & Closures",
          div(
            style = "background-color: #f7fbff; padding: 12px; border-radius: 6px; margin-bottom: 15px;",

            h4("What this map shows", style = "margin-top: 0;"),

            p(
              "County shading shows Hope Scholarship take-up, West Virginia's education
              savings account program, which began paying out in school year 2022-23.
              Dots mark individual schools that have closed or are slated to close, colored
              by whether the closure came before or after Hope money started flowing.",
              style = "font-size: 13px;"
            ),

            p(
              HTML("<strong>Sidebar filters apply here.</strong> District and School Grade
              Level filter which closure dots appear; the Year range slider filters dots by
              the school's final year of operation. County shading reflects the Hope metric
              you pick below and is not affected by the sidebar filters, since Hope recipient
              counts are only published for SY 2022-23 through 2024-25."),
              style = "font-size: 13px;"
            ),

            hr(),

            div(
              style = "display: flex; gap: 20px; flex-wrap: wrap; align-items: flex-end;",

              div(
                style = "flex: 2; min-width: 300px;",
                selectInput(
                  "hope_metric",
                  "Color counties by",
                  choices  = setNames(names(HOPE_MEASURES),
                                      vapply(HOPE_MEASURES, `[[`, character(1), "label")),
                  selected = "rate",
                  width    = "100%"
                )
              ),

              div(
                style = "flex: 1; min-width: 180px;",
                radioButtons(
                  "hope_year",
                  "School year",
                  choices  = HOPE_YEARS,
                  selected = "2025",
                  inline   = TRUE
                )
              ),

              div(
                style = "flex: 1; min-width: 190px;",
                selectInput(
                  "hope_dot_mode",
                  "Show school dots",
                  choices = c(
                    "All closures"                = "all",
                    "Only closures since Hope"    = "post",
                    "Hide dots"                   = "none"
                  ),
                  selected = "all",
                  width    = "100%"
                )
              )
            ),

            p(
              HTML("The color scale is <strong>held fixed across all three years</strong>,
              so switching years shows the program actually growing rather than
              re-shading each year to look the same. Statewide recipients went
              2,333 &rarr; 5,443 &rarr; 10,530, so SY 2022-23 reads pale on purpose."),
              style = "font-size: 12px; color: #555; margin: 8px 0 0;"
            )
          ),

          plotOutput("hope_map", height = "620px"),

          div(
            style = "font-size: 11px; color: #666; margin-top: 10px; line-height: 1.5;",
            HTML(
              "Recipient counts come from the Hope Scholarship annual reports. Rates use
              Census Population Estimates Program school-age counts as the denominator.
              Closure records come from the curated school status file.
              <strong>Dot positions are approximate</strong> &mdash; the source data has no
              school coordinates, so each dot is scattered at random inside its own county.
              The county each dot belongs to and the number of dots per county are exact;
              the spot within the county is not."
            )
          ),

          hr(),

          h4("Counties in view", style = "margin-bottom: 4px;"),
          p("Sorted by the selected metric. Reflects the sidebar filters.",
            style = "font-size: 12px; color: #666;"),
          DTOutput("hope_county_table"),

          br(),

          h4("Schools behind the dots", style = "margin-bottom: 4px;"),
          p("Every school currently plotted, with its closure year and consolidation note.",
            style = "font-size: 12px; color: #666;"),
          DTOutput("hope_school_table")
        ),

        tabPanel(
          "Schools Closed by Year Maps (Cumulative)",
          plotOutput("cumulative_closure_maps")
        ),
        
        tabPanel(
          "Schools Closed by Year Maps",
          plotOutput("year_maps_grid")
        ),
        tabPanel(
          "Closure Timing Patterns",
          plotOutput("closure_histogram", height = "500px")
        ),
        tabPanel(
          "Enrollment Trends: Consolidation Year",
          div(
            style = "background-color: #f7fbff; padding: 12px; border-radius: 6px; margin-bottom: 15px;",
            
            h4("What this plot shows", style = "margin-top: 0;"),
            
            p(
              "These plots show how enrollment changes over time within each district, centered around the timing of school consolidation. 
      Each panel represents a district, and the dashed vertical line marks the first year a school closure occurs.",
              style = "font-size: 13px;"
            ),
            
            p(
              "The goal is to compare enrollment trends before (in blue) and after (in red) consolidation to understand how student populations change around these events.",
              style = "font-size: 13px;"
            ),
            
            hr(),
            
            h4("Using the School Grade Levels filter", style = "margin-top: 10px;"),
            
            tags$ul(
              style = "font-size: 13px;",
              
              tags$li(
                strong("Enrollment: "),
                "Filtering by School Grade Level will show enrollment for the selected school grade level(s) only (e.g., elementary school enrollment if 'Elementary' is selected)."
              ),
              
              tags$li(
                strong("Consolidation timing: "),
                "The dashed line marks the first closure of the selected school grade level(s) in that district."
              ),
              
              tags$li(
                strong("Districts shown: "),
                "Only districts with at least one closure of the selected school grade level(s) are included."
              )
            )
              ),
          plotOutput("did_plot_1")
        ),
        
        tabPanel(
          "Enrollment Trends: Year Before",
          div(
            style = "background-color: #f7fbff; padding: 12px; border-radius: 6px; margin-bottom: 15px;",
            
            h4("What this plot shows", style = "margin-top: 0;"),
            
            p(
              "These plots show enrollment trends leading up to school consolidation. 
      The dashed vertical line is shifted one year earlier than the first closure, allowing you to examine changes just before consolidation occurs.",
              style = "font-size: 13px;"
            ),
            
            p(
              "This helps highlight whether enrollment was already declining prior to the first school closure.",
              style = "font-size: 13px;"
            )
            ),
            
          plotOutput("did_plot_2")
        ),
        
        tabPanel(
          "Enrollment Trends: Compared with Population",
          div(
            style = "background-color: #f7fbff; padding: 12px; border-radius: 6px; margin-bottom: 15px;",
            
            h4("How to read the plot below", style = "margin-top: 0;"),
            
            #  Intro (before example)
            p(
              "The plot below shows district enrollment alongside county population over time. 
    Because these measures are on very different scales, both are indexed to 100 in the first year shown for each district. 
    This allows them to be displayed on the same graph and compared more easily.",
              style = "font-size: 13px;"
            ),
            
            p(
              "After indexing, values represent percent change relative to the starting year. 
    For instance, a value of 90 indicates a 10% decline from the baseline of 100. The table below shows an example to further explain this.",
              style = "font-size: 13px; color: #555;"
            ),
            
            #  Example table
            HTML("
  <table style='border-collapse: collapse; width: 100%; font-size: 13px; margin-top: 10px;'>
    <tr>
      <th style='border-bottom: 1px solid #ccc; text-align: left;'>Year</th>
      <th style='border-bottom: 1px solid #ccc; text-align: left;'>School Enrollment</th>
      <th style='border-bottom: 1px solid #ccc; text-align: left;'>Total Population</th>
      <th style='border-bottom: 1px solid #ccc; text-align: left;'>Enrollment Index</th>
      <th style='border-bottom: 1px solid #ccc; text-align: left;'>Population Index</th>
    </tr>
    <tr>
      <td>2015</td>
      <td>2,000</td>
      <td>60,000</td>
      <td>100</td>
      <td>100</td>
    </tr>
    <tr>
      <td>2016</td>
      <td>1,800</td>
      <td>59,000</td>
      <td>90</td>
      <td>98.3</td>
    </tr>
  </table>
  "),
            
            # Explanation of example
            p(
              "In this example, from the year 2015 to 2016, school enrollment declines by 10% (from 2,000 students to 1,800 students, or an enrollment index from 100 to 90), while 
              population only declines by about 1.7% (from 60,000 people to 59,000 people, or a population index from 100 to 98.3). 
    This shows that enrollment is falling faster than the underlying population.",
              style = "font-size: 13px; color: #555; margin-top: 10px;"
            )
          ),
          plotOutput("did_plot_pop")
        )
      )
    )
  )
)

# =========================
# 5. SERVER
# =========================
server <- function(input, output, session) {
  
  facet_plot_height <- function(df, ncol = 3,
                                row_height = 200,
                                min_height = 450) {
    
    n_panels <- dplyr::n_distinct(df$facet_label)
    
    n_rows <- ceiling(n_panels / ncol)
    
    max(min_height, n_rows * row_height)
  }
  
  map_plot_height <- function(df, panels_per_row = 3,
                              row_height = 300,
                              min_height = 450) {
    n_panels <- dplyr::n_distinct(df$Year)
    n_rows <- ceiling(n_panels / panels_per_row)
    max(min_height, n_rows * row_height)
  }
  
  observeEvent(input$district_filter, {
    selected <- input$district_filter
    
    if ("All" %in% selected && length(selected) > 1) {
      updateSelectInput(
        session,
        "district_filter",
        selected = setdiff(selected, "All")
      )
    }
    
    if (length(selected) == 0) {
      updateSelectInput(
        session,
        "district_filter",
        selected = "All"
      )
    }
  })
  
  observeEvent(input$school_type_filter, {
    selected <- input$school_type_filter
    
    if ("All" %in% selected && length(selected) > 1) {
      updateSelectInput(
        session,
        "school_type_filter",
        selected = setdiff(selected, "All")
      )
    }
    
    if (length(selected) == 0) {
      updateSelectInput(
        session,
        "school_type_filter",
        selected = "All"
      )
    }
  })
  
  
  filtered_school_status <- reactive({
    df <- school_status
    
    if (!is.null(input$district_filter) && !("All" %in% input$district_filter)) {
      df <- df %>% filter(District %in% input$district_filter)
    }
    
    if (!is.null(input$school_type_filter) && !("All" %in% input$school_type_filter)) {
      df <- df %>% filter(Type %in% input$school_type_filter)
    }

    df
  })

  # =========================
  # HOPE SCHOLARSHIP & CLOSURES MAP
  # =========================
  # Dots respond to all three sidebar filters plus the tab's own dot-mode select.
  # Pending closures have no end_year, so the year slider cannot filter them;
  # they are kept whenever the slider still reaches the present.
  # Sidebar filters only. Kept separate from the dot-visibility toggle so that
  # hiding the dots does not also blank out the "Schools closed" choropleth.
  hope_dots_in_scope <- reactive({
    df <- hope_dots
    if (nrow(df) == 0) return(df)

    if (!is.null(input$district_filter) && !("All" %in% input$district_filter)) {
      df <- df %>% filter(District %in% input$district_filter)
    }

    if (!is.null(input$school_type_filter) && !("All" %in% input$school_type_filter)) {
      df <- df %>% filter(Type %in% input$school_type_filter)
    }

    yr <- input$year_range
    if (!is.null(yr)) {
      last_close <- suppressWarnings(max(hope_dots$close_year, na.rm = TRUE))
      if (!is.finite(last_close)) last_close <- yr[2]
      df <- df %>%
        filter(
          (!is.na(close_year) & close_year >= yr[1] & close_year <= yr[2]) |
            (is.na(close_year) & yr[2] >= last_close)
        )
    }

    df
  })

  # Adds the tab's own dot-mode select on top of the sidebar filters.
  hope_dots_filtered <- reactive({
    df <- hope_dots_in_scope()
    if (identical(input$hope_dot_mode, "post")) df <- df %>% filter(dot_era != "pre")
    if (identical(input$hope_dot_mode, "none")) df <- df[0, , drop = FALSE]
    df
  })

  # County polygons joined to the Hope metrics. The "n_closed" metric counts the
  # closures inside the sidebar's district/type/year scope, so the shading tracks
  # the same records as the dots without being tied to whether dots are visible.
  hope_map_sf <- reactive({
    closed_in_range <- hope_dots_in_scope() %>%
      filter(dot_era != "pending") %>%
      count(District, name = "n_closed")

    tbl <- hope_county_base %>%
      left_join(closed_in_range, by = "District") %>%
      mutate(n_closed = tidyr::replace_na(n_closed, 0L))

    district_shapes %>%
      mutate(District = stringr::str_squish(stringr::str_remove(
        NAME, " County School District$| County Schools$| Schools$| School District$"
      ))) %>%
      select(District) %>%
      left_join(tbl, by = "District")
  })

  # Choropleth + closure dots, drawn with ggplot/geom_sf to match the other map
  # tabs and to avoid taking on leaflet as a dependency.
  output$hope_map <- renderPlot({
    measure_id <- input$hope_metric %||% "rate"
    year_id    <- input$hope_year   %||% "2025"
    meta       <- HOPE_MEASURES[[measure_id]]
    col        <- paste0(meta$prefix, year_id)
    shp        <- hope_map_sf()

    req(nrow(shp) > 0, col %in% names(shp))

    shp$metric_value <- shp[[col]]
    dots <- hope_dots_filtered()

    p <- ggplot(shp) +
      geom_sf(aes(fill = metric_value), color = "white", linewidth = 0.25) +
      scale_fill_gradient(
        low      = "#f2ecf9",
        high     = "#4c2b7a",
        na.value = "#d9d9d9",
        # Fixed across years so the year selector reveals growth, not a rescale.
        limits   = HOPE_LIMITS[[measure_id]],
        labels   = scales::label_number(accuracy = meta$accuracy),
        name     = meta$legend
      )

    if (nrow(dots) > 0) {
      # Single-color dots. The white halo underneath keeps them readable on the
      # darkest counties without needing a color encoding.
      p <- p +
        geom_point(data = dots, aes(x = lon, y = lat),
                   colour = "white", size = 2.6, show.legend = FALSE) +
        geom_point(data = dots, aes(x = lon, y = lat),
                   colour = HOPE_DOT_COLOR, size = 1.7, show.legend = FALSE)
    }

    year_label <- names(HOPE_YEARS)[match(year_id, HOPE_YEARS)]

    # The statewide total is spelled out because a fixed color scale makes the
    # early years pale by design; the number keeps the magnitude unambiguous.
    statewide <- sum(hope_county_base[[paste0("hope_", year_id)]], na.rm = TRUE)

    # Stands in for the dot legend, which is gone now that all dots share a color.
    subtitle <- sprintf(
      "%s statewide recipients  ·  dots: %s school closure%s%s",
      scales::comma(statewide),
      scales::comma(nrow(dots)),
      ifelse(nrow(dots) == 1, "", "s"),
      if (!is.null(input$year_range)) {
        sprintf(", %d–%d", input$year_range[1], input$year_range[2])
      } else ""
    )

    p +
      labs(
        title    = paste0(meta$label, "  —  ", year_label),
        subtitle = subtitle,
        caption  = paste0(
          "Dots are scattered inside their county, not placed at real addresses. ",
          "Rate denominators use ", hope_pop_year, " Census PEP school-age population."
        )
      ) +
      coord_sf(expand = FALSE) +
      theme_void(base_size = 13) +
      theme(
        plot.title    = element_text(size = 14, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 11, colour = "#666666", hjust = 0.5),
        plot.caption  = element_text(size = 9,  colour = "#888888", hjust = 0.5),
        legend.position = "bottom",
        legend.box      = "vertical",
        legend.title    = element_text(size = 10),
        legend.text     = element_text(size = 9)
      )
  })

  # County-level numbers behind the shading. Shows all three years side by side
  # regardless of which one is mapped, sorted by the year currently selected.
  output$hope_county_table <- renderDT({
    measure_id <- input$hope_metric %||% "rate"
    year_id    <- input$hope_year   %||% "2025"
    sort_col   <- paste0(HOPE_MEASURES[[measure_id]]$prefix, year_id)

    shp <- hope_map_sf() %>% sf::st_drop_geometry()
    req(sort_col %in% names(shp))

    shp %>%
      arrange(desc(.data[[sort_col]])) %>%
      transmute(
        County                 = District,
        `Recip. 22-23`         = hope_2023,
        `Recip. 23-24`         = hope_2024,
        `Recip. 24-25`         = hope_2025,
        `Per 100, 22-23`       = round(rate_2023, 2),
        `Per 100, 23-24`       = round(rate_2024, 2),
        `Per 100, 24-25`       = round(rate_2025, 2),
        `Growth 22-23→24-25`   = growth,
        `Growth %`             = round(growth_pct),
        `School-age pop.`      = school_age_pop,
        `Schools closed`       = n_closed
      ) %>%
      datatable(
        rownames = FALSE,
        options  = list(pageLength = 10, scrollX = TRUE,
                        order = list())   # keep the arrange() order
      )
  })

  # The detail the map dots cannot carry: which schools they actually are.
  output$hope_school_table <- renderDT({
    dots <- hope_dots_filtered()

    validate(need(nrow(dots) > 0, "No closures match the current filters."))

    dots %>%
      arrange(District, desc(close_year), School) %>%
      transmute(
        County         = District,
        School         = School,
        `Grade level`  = Type,
        `Final year`   = ifelse(is.na(close_year), "pending", as.character(close_year)),
        Status         = unname(HOPE_DOT_LABELS[as.character(dot_era)]),
        Note           = dot_note
      ) %>%
      datatable(
        rownames = FALSE,
        filter   = "top",
        options  = list(pageLength = 10, scrollX = TRUE, order = list())
      )
  })

#  filtered_district_panel <- reactive({
#    keep_districts <- filtered_school_status() %>%
#      distinct(District) %>%
#      pull(District)
  
  filtered_district_panel <- reactive({
    
    selected_types <- input$school_type_filter
    
    if (!is.null(selected_types) &&
        length(selected_types) > 1 &&
        "All" %in% selected_types) {
      selected_types <- setdiff(selected_types, "All")
    }
    
    # Enrollment data: all students in selected school type(s)
    comp_df <- school_comp_clean
    
    # Closure timing data: closures in selected school type(s)
    status_df <- school_status %>%
      filter(closed == TRUE, !is.na(end_year))
    
    # Apply school type filter
    if (!is.null(selected_types) && !("All" %in% selected_types)) {
      comp_df <- comp_df %>%
        filter(Type %in% selected_types)
      
      status_df <- status_df %>%
        filter(Type %in% selected_types)
    }
    
    # Apply district filter
    if (!is.null(input$district_filter) && !("All" %in% input$district_filter)) {
      comp_df <- comp_df %>%
        filter(District %in% input$district_filter)
      
      status_df <- status_df %>%
        filter(District %in% input$district_filter)
    }
    
    # Apply year filter to enrollment only
    comp_df <- comp_df %>%
      filter(
        Year >= input$year_range[1],
        Year <= input$year_range[2]
      )
    
    # District-level enrollment for selected type(s)
    enr_df <- comp_df %>%
      group_by(District, Year) %>%
      summarise(
        enrollment = sum(headcount, na.rm = TRUE),
        .groups = "drop"
      )
    
    # District-level first closure year for selected type(s)
    closure_df <- status_df %>%
      group_by(District) %>%
      summarise(
        first_cons_year = min(end_year, na.rm = TRUE),
        last_cons_year = max(end_year, na.rm = TRUE),
        n_closed = n(),
        .groups = "drop"
      )
    
    validate(
      need(nrow(closure_df) > 0,
           "No districts have closures for the selected filters.")
    )
    
    out <- enr_df %>%
      inner_join(closure_df, by = "District") %>%
      left_join(census, by = c("District", "Year"))
    
    validate(
      need(nrow(out) > 0,
           "No enrollment data match the selected district, school grade level, and year range.")
    )
    
    out
  })
  
  
  filtered_map_sf <- reactive({
    keep_districts <- filtered_school_status() %>%
      distinct(District) %>%
      pull(District)
    
    df <- district_map_sf %>%
      filter(District %in% keep_districts)
    
    validate(need(nrow(df) > 0, "No districts match the current filters."))
    df
  })
  
  filtered_school_comp <- reactive({
    keep_districts <- filtered_school_status() %>%
      distinct(District) %>%
      pull(District)
    
    school_comp_clean %>%
      filter(
        District %in% keep_districts,
        Year >= input$year_range[1],
        Year <= input$year_range[2]
      )
  })
  
  # ---- Real closures for the District Summary Table -----------------------
  # Closure status is read from the curated workbook's own `closed` column; the
  # spreadsheets are never modified.
  #
  # When WVDE reissues a school code, the workbook ends up holding TWO rows for
  # the same school: the retired code marked closed, and the successor code
  # marked open. Wetzel's 2025 reconstitution is the clearest case --
  # 92504 Valley High (closed, end 2025) sits alongside 92506 Valley High
  # (open, start 2026), and likewise 92502 / 92505 for Magnolia. Neither school
  # actually closed; only the identifier changed.
  #
  # That open row is the dataset's own evidence, so we use it rather than a
  # hand-maintained list: a closed row is suppressed when another row in the
  # same district carries the same school name and starts after the closure
  # year. Nothing is hardcoded, and new reconstitutions are handled the moment
  # the successor row appears in the data.
  real_closures_curated <- reactive({
    status <- filtered_school_status()

    closed_rows <- status %>%
      filter(Closed_curated, !is.na(End_year_curated))

    if (nrow(closed_rows) == 0) return(closed_rows)

    successors <- status %>%
      filter(!Closed_curated, !is.na(start_year)) %>%
      select(District, School, successor_start = start_year)

    suppressed <- closed_rows %>%
      inner_join(successors, by = c("District", "School")) %>%
      filter(successor_start > End_year_curated) %>%
      distinct(Schl_ID)

    closed_rows %>% anti_join(suppressed, by = "Schl_ID")
  })

  output$desc_table <- renderDT({
    desc_df <- filtered_school_comp() %>%
      group_by(Year, District) %>%
      summarise(
        `Total # Students` = sum(headcount, na.rm = TRUE),
        `Total # Schools` = n_distinct(School),
        .groups = "drop"
      ) %>%
      left_join(
        real_closures_curated() %>%
          group_by(District, Year = End_year_curated) %>%
          summarise(
            `# Schools Closed` = n(),
            `Schools Closed (Names)` = paste(sort(unique(School)), collapse = "; "),
            .groups = "drop"
          ),
        by = c("District", "Year")
      ) %>%
      mutate(
        `# Schools Closed` = tidyr::replace_na(`# Schools Closed`, 0),
        `Schools Closed (Names)` = ifelse(
          is.na(`Schools Closed (Names)`),
          "None",
          `Schools Closed (Names)`
        )
      ) %>%
      arrange(District, Year)
    
    
    DT::datatable(
      desc_df,
      rownames = FALSE,
      options = list(
        pageLength = 16,
        scrollX = TRUE
      )
    )
  })
  
  plot_data_cons <- reactive({
    build_pre_post_plot_data(filtered_district_panel(), offset = 0)
  })
  
  plot_data_pre <- reactive({
    build_pre_post_plot_data(filtered_district_panel(), offset = -1)
  })
  
  output$did_plot_1 <- renderPlot({
    
    df <- plot_data_cons()
    req(nrow(df) > 0)
    
    vlines <- df %>%
      distinct(facet_label, threshold)
    
    ggplot(df, aes(x = Year, y = enrollment, color = period, group = 1)) +
      geom_line(linewidth = 0.7) +
      geom_point(size = 1.8) +
      geom_vline(
        data = vlines,
        aes(xintercept = threshold + 0.5),
        inherit.aes = FALSE,
        linetype = "dashed",
        color = "gray50",
        linewidth = 0.4
      ) +
      facet_wrap(~facet_label, scales = "free_y", ncol = 3) +
      scale_color_manual(values = c("pre" = "#2b6cb0", "post" = "#c53030")) +
      theme_minimal(base_size = 10) +
      theme(aspect.ratio = 0.7)
    
  }, height = function() {
    facet_plot_height(plot_data_cons())
  })
  

  output$did_plot_2 <- renderPlot({
    df <- plot_data_pre()
    req(nrow(df) > 0)
    
    vlines <- df %>%
      distinct(facet_label, threshold)
    
    ggplot(df, aes(x = Year, y = enrollment, color = period, group = 1)) +
      geom_line(linewidth = 0.7) +
      geom_point(size = 1.8) +
      geom_vline(
        data = vlines,
        aes(xintercept = threshold + 0.5),
        inherit.aes = FALSE,
        linetype = "dashed",
        color = "gray50",
        linewidth = 0.4
      ) +
      facet_wrap(~facet_label, scales = "free_y", ncol = 3) +
      scale_color_manual(values = c("pre" = "#2b6cb0", "post" = "#c53030")) +
      labs(
        title = "Pre/post enrollment (threshold = one year before first consolidation)",
        x = NULL,
        y = "Enrollment",
        color = NULL
      ) +
      theme_minimal(base_size = 10) +
      theme(
        legend.position = "top",
        strip.text = element_text(size = 8),
        axis.text = element_text(size = 7),
        axis.title.y = element_text(size = 10),
        aspect.ratio = 0.7
      )
  }, height = function() {
    facet_plot_height(plot_data_pre())
  })
  
  
  year_maps_sf <- reactive({
    keep_districts <- filtered_school_status() %>%
      distinct(District) %>%
      pull(District)
    
    shape_df <- district_shapes %>%
      mutate(
        District = stringr::str_remove(NAME, " County School District$| County Schools$| Schools$| School District$"),
        District = stringr::str_squish(District)
      )
    
    panel_df <- district_panel %>%
      filter(
        District %in% keep_districts,
        Year >= input$year_range[1],
        Year <= input$year_range[2]
      ) %>%
      select(District, Year, enrollment)
    
    out <- shape_df %>%
      left_join(panel_df, by = "District") %>%
      filter(!is.na(Year))
    
    validate(need(nrow(out) > 0, "No districts/years match the current filters."))
    out
  })
  
  output$year_maps_grid <- renderPlot({
    
    keep_districts <- filtered_school_status() %>%
      distinct(District) %>%
      pull(District)
    
    closure_map_df <- build_closure_year_map_data(
      school_status = filtered_school_status(),
      district_shapes = district_shapes,
      year_min = input$year_range[1],
      year_max = input$year_range[2]
    ) %>%
      filter(District %in% keep_districts)
    
    req(nrow(closure_map_df) > 0)
    
    closure_map_df$Year <- factor(closure_map_df$Year)
    
    ggplot(closure_map_df) +
      geom_sf(aes(fill = n_closed_that_year), color = "gray50", linewidth = 0.15) +
      geom_sf_text(
        data = closure_map_df %>% filter(n_closed_that_year > 0),
        aes(label = District),
        size = 3
      ) +
      facet_wrap(~Year, ncol = 3) +
      scale_fill_gradient(
        low = "#f7fbff",
        high = "red3",
        limits = c(0, 10),
        breaks = seq(0, 10, by = 2),
        na.value = "#d9d9d9",
        oob = scales::squish
      ) +
      labs(
        title = "Number of Schools Closed Within Each District by Year",
        fill = "# Closed"
      ) +
      theme_void() +
      theme(
        strip.text = element_text(size = 9),
        plot.title = element_text(size = 12, hjust = 0.5),
        legend.position = "bottom",
        aspect.ratio = 0.7
      )
  }, height = function() {
    
    keep_districts <- filtered_school_status() %>%
      distinct(District) %>%
      pull(District)
    
    closure_map_df <- build_closure_year_map_data(
      school_status = filtered_school_status(),
      district_shapes = district_shapes,
      year_min = input$year_range[1],
      year_max = input$year_range[2]
    ) %>%
      filter(District %in% keep_districts)
    
    map_plot_height(closure_map_df, panels_per_row = 3)
  })
  
# test pop
  # Build the same data used in the app
#  df <- build_pre_post_plot_data(district_panel, offset = 0)
  
  # Optional: filter to a few districts so it's not overwhelming
#  df <- df %>%
#    filter(District %in% unique(District)[1:6])
#  df <- df %>%
#    group_by(facet_label) %>%
#    mutate(
#      enrollment_index = 100 * enrollment / first(enrollment),
#      population_index = 100 * population / first(population)
#    ) %>%
#    ungroup()
  
  
  output$did_plot_pop <- renderPlot({
    
    df <- plot_data_cons()
    req(nrow(df) > 0)
    
    df <- df %>%
      arrange(facet_label, Year) %>%
      group_by(facet_label) %>%
      mutate(
        enrollment_base = first(enrollment[!is.na(enrollment) & enrollment > 0]),
        population_base = first(population[!is.na(population) & population > 0]),
        enrollment_index = 100 * enrollment / enrollment_base,
        population_index = 100 * population / population_base,
        # School-age population is indexed against its own first available
        # year. That base may differ from the population base when ACS
        # coverage starts later, which is fine: each series answers "percent
        # change from its own starting point."
        school_age_base = if (all(is.na(school_age_pop))) {
          NA_real_
        } else {
          first(school_age_pop[!is.na(school_age_pop) & school_age_pop > 0])
        },
        school_age_index = 100 * school_age_pop / school_age_base,
        school_age_pep_base = if (all(is.na(school_age_pop_pep))) {
          NA_real_
        } else {
          first(school_age_pop_pep[!is.na(school_age_pop_pep) &
                                     school_age_pop_pep > 0])
        },
        school_age_pep_index = 100 * school_age_pop_pep / school_age_pep_base
      ) %>%
      ungroup() %>%
      filter(
        !is.na(enrollment_index),
        !is.na(population_index)
      )
    
    req(nrow(df) > 0)
    
    vlines <- df %>%
      distinct(facet_label, threshold)

    # The school-age series is optional (see wv_school_age_2011_2024.csv at the
    # top of this file). When it is absent the layer must be dropped entirely
    # rather than fed an empty frame: a constant colour aesthetic against zero
    # rows is a length mismatch and ggplot errors out. Its legend key is
    # dropped alongside it so the legend never advertises a missing line.
    # School-age 5-17 is plotted from PEP rather than ACS. Both were compared
    # over all 770 county-years (see census_data.qmd): they correlate at 0.999,
    # but ACS is noisier in small counties (mean |YoY| 1.89% vs 1.71%, driven by
    # sampling error above 14% of the estimate in Gilmer, Wirt and Calhoun) and
    # lags roughly two years, so in a declining population it overstates the
    # current level by about 2%. PEP is annual and point-in-time, which matters
    # here because the question is about timing relative to closures.
    # The ACS series is still loaded and joined; re-adding its layer is a small
    # edit if you want both on the chart again.
    school_age_pep_df  <- df %>% filter(!is.na(school_age_pep_index))
    has_school_age_pep <- nrow(school_age_pep_df) > 0

    series_breaks <- c("pre", "post", "Total population")
    series_labels <- c("Enrollment (pre-closure)",
                       "Enrollment (post-closure)",
                       "Total population (PEP)")
    if (has_school_age_pep) {
      series_breaks <- c(series_breaks, "School-age PEP")
      series_labels <- c(series_labels, "School-age 5-17 (PEP)")
    }

    school_type_label <- ifelse(
      is.null(input$school_type_filter) || "All" %in% input$school_type_filter,
      "all school types",
      paste(input$school_type_filter, collapse = " + ")
    )

    ggplot(df, aes(x = Year)) +
      geom_line(
        aes(y = enrollment_index, color = period, group = 1),
        linewidth = 0.7
      ) +
      geom_point(
        aes(y = enrollment_index, color = period),
        size = 1.8
      ) +
      geom_line(
        aes(y = population_index, color = "Total population", group = 1),
        linewidth = 0.9
      ) +
      (if (has_school_age_pep) {
        geom_line(
          data = school_age_pep_df,
          aes(y = school_age_pep_index,
              color = "School-age PEP",
              group = 1),
          linewidth = 0.9,
          linetype = "22"
        )
      } else NULL) +
      geom_vline(
        data = vlines,
        aes(xintercept = threshold + 0.5),
        inherit.aes = FALSE,
        linetype = "dashed",
        color = "gray50",
        linewidth = 0.4
      ) +
      facet_wrap(~facet_label, ncol = 3, scales = "free_y") +
      scale_color_manual(
        values = c(
          "pre"              = "#2b6cb0",
          "post"             = "#c53030",
          "Total population" = "darkgray",
          "School-age PEP"   = "#2f855a"
        ),
        breaks = series_breaks,
        labels = series_labels
      ) +
      labs(
        title = "Enrollment and Population Trends Around First Closure",
        subtitle = paste0(
          "Enrollment reflects ", school_type_label,
          ". All series indexed to 100 at their first available year.\n",
          "Population series are Census PEP; note the 2020 vintage rebenchmark ",
          "creates a small step in both."
        ),
        x = NULL,
        y = "Index (Base Year = 100)",
        color = NULL
      ) +
      theme_minimal(base_size = 10) +
      theme(
        legend.position = "top",
        strip.text = element_text(size = 8),
        axis.text = element_text(size = 7),
        aspect.ratio = 0.7
      )
  }, height = function() {
    facet_plot_height(plot_data_cons())
  })
  
  output$closure_histogram <- renderPlot({
    
    closure_year_df <- filtered_school_status() %>%
      filter(
        closed,
        !is.na(end_year),
        end_year >= input$year_range[1],
        end_year <= input$year_range[2]
      ) %>%
      count(end_year, name = "n_closed")
    
    req(nrow(closure_year_df) > 0)
    
    ggplot(closure_year_df, aes(x = end_year, y = n_closed)) +
      geom_col(fill = "skyblue3", width = 0.8) +
      geom_text(
        aes(label = n_closed),
        vjust = -0.3,
        size = 3
      ) +
      scale_x_continuous(
        breaks = seq(input$year_range[1], input$year_range[2], by = 1)
      ) +
      coord_cartesian(
        xlim = c(input$year_range[1] - 0.5, input$year_range[2] + 0.5)
      ) +
      labs(
        title = "Number of School Closures by Year",
        x = "Year",
        y = "# Schools Closed"
      ) +
      theme_minimal(base_size = 12) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1)
      )
  })
  
  output$cumulative_closure_maps <- renderPlot({
    
    keep_districts <- filtered_school_status() %>%
      distinct(District) %>%
      pull(District)
    
    cumulative_map_df <- build_cumulative_closure_map_data(
      school_status = filtered_school_status(),
      district_shapes = district_shapes,
      year_min = input$year_range[1],
      year_max = input$year_range[2]
    ) %>%
      filter(District %in% keep_districts)
    
    req(nrow(cumulative_map_df) > 0)
    
    cumulative_map_df$Year <- factor(cumulative_map_df$Year)
    
    ggplot(cumulative_map_df) +
      geom_sf(aes(fill = cumulative_closed), color = "gray50", linewidth = 0.15) +
      geom_sf_text(
        data = cumulative_map_df %>% filter(cumulative_closed > 0),
        aes(label = District),
        size = 2
      ) +
      facet_wrap(~Year, ncol = 3) +
      scale_fill_gradient(
        low = "#f7fbff",
        high = "red3",
        limits = c(0, 10),
        oob = scales::squish,
        breaks = seq(0, 10, by = 2),
        labels = c("0", "2", "4", "6", "8", "10+"),
        na.value = "#d9d9d9"
      ) +
      labs(
        title = "Cumulative Number of Schools Closed Within Each District by Year",
        fill = "# Closed"
      ) +
      theme_void() +
      theme(
        strip.text = element_text(size = 9),
        plot.title = element_text(size = 12, hjust = 0.5),
        legend.position = "bottom"
      )
  }, height = function() {
    
    keep_districts <- filtered_school_status() %>%
      distinct(District) %>%
      pull(District)
    
    closure_map_df <- build_closure_year_map_data(
      school_status = filtered_school_status(),
      district_shapes = district_shapes,
      year_min = input$year_range[1],
      year_max = input$year_range[2]
    ) %>%
      filter(District %in% keep_districts)
    
    map_plot_height(closure_map_df, panels_per_row = 3)
  })
}
  
# =========================
# 6. RUN APP
# =========================
shinyApp(ui = ui, server = server)
